version: '3.8'

services:
  social-media-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-media-portal
    restart: unless-stopped
    expose:
      - 3008:3000  # Only expose to other containers, not host
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=file:/app/data/prod.db
      - NEXT_AUTH_URL=${NEXT_AUTH_URL}
      - NEXT_AUTH_CLIENT_ID=${NEXT_AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - NEXT_BASE_URL=${NEXT_BASE_URL}
      - NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
      - NEXT_PUBLIC_AUTH_CLIENT_ID=${NEXT_PUBLIC_AUTH_CLIENT_ID}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - GETLATE_API_KEY=${GETLATE_API_KEY}
      - GETLATE_API_URL=${GETLATE_API_URL}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backup:
    image: alpine:latest
    container_name: social-media-backup
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
    environment:
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-0 2 * * *}
    command: >
      sh -c "
      apk add --no-cache sqlite tar &&
      echo '${BACKUP_SCHEDULE} cd /backups && sqlite3 /data/prod.db \".backup backup-\$$(date +%Y%m%d-%H%M%S).db\" && find /backups -name \"backup-*.db\" -mtime +7 -delete' | crontab - &&
      crond -f
      "
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
