version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-media-portal
    restart: unless-stopped
    network_mode: host
    environment:
      # Node environment
      - NODE_ENV=production
      
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # NextAuth Authentication
      - NEXT_AUTH_URL=${NEXT_AUTH_URL}
      - NEXT_AUTH_CLIENT_ID=${NEXT_AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - NEXT_BASE_URL=${NEXT_BASE_URL}
      - NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}
      - NEXT_PUBLIC_AUTH_CLIENT_ID=${NEXT_PUBLIC_AUTH_CLIENT_ID}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      
      # NextAuth Security
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      
      # Encryption
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      
      # Port (if specified)
      - PORT=${PORT}
    volumes:
      # Persist SQLite database
      - ./data:/app/data
      # Persist Prisma files
      - ./prisma:/app/prisma
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:${PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s